{
  "formatVersion": "1.1",
  "component": {
    "group": "in.juspay",
    "module": "airborne",
    "version": "2.2.8-xota.test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "in.juspay",
          "module": "hyperutil",
          "version": {
            "requires": "2.2.5-xota.05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "airborne-2.2.8-xota.test.aar",
          "url": "airborne-2.2.8-xota.test.aar",
          "size": 208254,
          "sha512": "3cace52f213b4144f1dca2a8a6d9ea7ee99a946072fda818ec35fc3332356151c179d763754aa471768e34ef96a0472ac9b6c9f56b7eab3a637e78993917b96c",
          "sha256": "88fe6821beade7c135d3f3c48b582e4294aa6ae2734d0d9f806c3adcbedede1f",
          "sha1": "1eaad2b2ce45d6afae5005548b4f780488d7ac25",
          "md5": "daa61bf40f71776814f276ca79646f2c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "in.juspay",
          "module": "hyperutil",
          "version": {
            "requires": "2.2.5-xota.05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "airborne-2.2.8-xota.test.aar",
          "url": "airborne-2.2.8-xota.test.aar",
          "size": 208254,
          "sha512": "3cace52f213b4144f1dca2a8a6d9ea7ee99a946072fda818ec35fc3332356151c179d763754aa471768e34ef96a0472ac9b6c9f56b7eab3a637e78993917b96c",
          "sha256": "88fe6821beade7c135d3f3c48b582e4294aa6ae2734d0d9f806c3adcbedede1f",
          "sha1": "1eaad2b2ce45d6afae5005548b4f780488d7ac25",
          "md5": "daa61bf40f71776814f276ca79646f2c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "airborne-2.2.8-xota.test-sources.jar",
          "url": "airborne-2.2.8-xota.test-sources.jar",
          "size": 120019,
          "sha512": "6f6dcbcb6b797317c75df643f9c8ddb157e7c00080d98779e467b954f643be32b55a278d8e24aef9b6787d1efaaa109747c638695be52a85ae1c9b41bf6f6a45",
          "sha256": "3d7f558a6bacb42b265ecf2f319bc4e06ceae870b2753e270bf0c6a809d28ccc",
          "sha1": "c46378389e5841ac440e43d45952bdc1ff3bfae4",
          "md5": "ed6d9900602bc7f6af5a83cc201255c9"
        }
      ]
    }
  ]
}
