{
  "formatVersion": "1.1",
  "component": {
    "group": "in.juspay",
    "module": "airborne",
    "version": "2.2.8-xota.test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "in.juspay",
          "module": "hyperutil",
          "version": {
            "requires": "2.2.5-xota.05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "airborne-2.2.8-xota.test.aar",
          "url": "airborne-2.2.8-xota.test.aar",
          "size": 209131,
          "sha512": "256c7642556752478baba27166edf0dcf1a6fecd0d828612b2629f6f3b66ca9604e197f301b0402fbba627cd34be2005242a4813300dd6025aafa540d68728b2",
          "sha256": "729601b5630e06ca4a70785484c88be54546f3229b85320cc4130e52d8f6e441",
          "sha1": "bf4598e93046902ad276e18eb6c3e890ea7fd492",
          "md5": "aae48d6678cda22f087b5037e040ebbc"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "in.juspay",
          "module": "hyperutil",
          "version": {
            "requires": "2.2.5-xota.05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "airborne-2.2.8-xota.test.aar",
          "url": "airborne-2.2.8-xota.test.aar",
          "size": 209131,
          "sha512": "256c7642556752478baba27166edf0dcf1a6fecd0d828612b2629f6f3b66ca9604e197f301b0402fbba627cd34be2005242a4813300dd6025aafa540d68728b2",
          "sha256": "729601b5630e06ca4a70785484c88be54546f3229b85320cc4130e52d8f6e441",
          "sha1": "bf4598e93046902ad276e18eb6c3e890ea7fd492",
          "md5": "aae48d6678cda22f087b5037e040ebbc"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "airborne-2.2.8-xota.test-sources.jar",
          "url": "airborne-2.2.8-xota.test-sources.jar",
          "size": 124001,
          "sha512": "3f7531596c51b2c1adfc17bc117108844ddfd0c896cd12e38d2e71c339bee02c7eca016ad48ce16caa78b29c2c005e9d5b5d98078c1ece62ddfe94c5fd1f8e1d",
          "sha256": "5bd7da2d922067eba2e74bb8ff1d33a9b84965b7a9d15445ddabb9b2328c2a76",
          "sha1": "1152250ea2136a852f5cdd1ce6e725f2d429e8cc",
          "md5": "b22e2b26d7c4fc795f3d5ac141ca40a8"
        }
      ]
    }
  ]
}
