{
  "formatVersion": "1.1",
  "component": {
    "group": "com.movingtech",
    "module": "airborne",
    "version": "2.2.8-xota.test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "in.juspay",
          "module": "hyperutil",
          "version": {
            "requires": "2.2.5-xota.05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "airborne-2.2.8-xota.test.aar",
          "url": "airborne-2.2.8-xota.test.aar",
          "size": 208506,
          "sha512": "e9ea34398fed7c6ee87d79d8e8d1b7eb9e8683eaa21013594dbd63583d81815354cd6024f7895ac4371d713383a92e6f220c79961e92bb6a27bb4caad7ca5c19",
          "sha256": "3ccd4bce318117bd9701cc087fcc70ea55d85b6e9868a23e89bffb26ee5f83b7",
          "sha1": "67b7003c74c31ca61f33c3bc5565680d4467d03a",
          "md5": "2963da14ddf0eb5029bd12dd1adcd814"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "in.juspay",
          "module": "hyperutil",
          "version": {
            "requires": "2.2.5-xota.05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "airborne-2.2.8-xota.test.aar",
          "url": "airborne-2.2.8-xota.test.aar",
          "size": 208506,
          "sha512": "e9ea34398fed7c6ee87d79d8e8d1b7eb9e8683eaa21013594dbd63583d81815354cd6024f7895ac4371d713383a92e6f220c79961e92bb6a27bb4caad7ca5c19",
          "sha256": "3ccd4bce318117bd9701cc087fcc70ea55d85b6e9868a23e89bffb26ee5f83b7",
          "sha1": "67b7003c74c31ca61f33c3bc5565680d4467d03a",
          "md5": "2963da14ddf0eb5029bd12dd1adcd814"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "airborne-2.2.8-xota.test-sources.jar",
          "url": "airborne-2.2.8-xota.test-sources.jar",
          "size": 120691,
          "sha512": "a877d5bafd3655ad27db99bde846ee336c2bc4a1a36b97a7cce28bbe42231a5643f463b189d5fed7d0699a333d9614386d29b469ea21d16970cd8f4aaebbca92",
          "sha256": "f7c322e33a4fd211bb2d48aab37dc4c1c90886e3987b981b23805e03f4a31b6b",
          "sha1": "8de3af7df992a5bb1dd2bffe03f8efa73194f522",
          "md5": "68a907d99288866cbb373795957a0727"
        }
      ]
    }
  ]
}
